icount/config/routes.rb
Icount::Application.routes.draw do
  resources :client do
    resources :report
  end

  resources :main, :only => [:index]

  # Root path
  root :to => 'main#index'

end

#, :only => [:index, :show, :new, :create, :update]
#, :only => [:new, :create, :index, :show, :update]

icount/app/models/client.rb
class Client < ActiveRecord::Base
  has_many :reports 

end

icount/app/models/iuser.rb
class Iuser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  after_create :assign_user_role

  def master?
    role == 'master'
  end

  def reguser?
    role == 'reguser'
  end

  private
    def assign_user_role
      self.role = 'reguser'
      self.save
    end
end

icount/app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :client

end

icount/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  
  include Pundit

  protect_from_forgery with: :exception

  before_action :authenticate_iuser!

end

icount/app/controllers/client_controller.rb
class ClientController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  def new
    @client = Client.new
  end

  # def create
  #   @client = Client.new(client_params)
  #   if @client.save
  #     redirect_to new_client_report_path(@client)
  #   end
  # end

  def create
    @client = Client.new(client_params)
    respond_to do |format|
      if @client.save
        format.html { redirect_to new_client_report_path(@client), notice: 'Client was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end


  def index
    @clients = Client.all
  end

  def show
    @client = Client.find(params[:id])
    @reports = @client.reports.all
  end

  def update
  end

  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to client_index_path }
      #format.json { head :no_content }
    end
  end

  private

  def set_client
    @client = Client.find(params[:id])
  end

  def client_params
    params.require(:client).permit(:name, :description)
  end

end

icount/app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

icount/app/controllers/report_controller.rb
require 'byebug'
class ReportController < ApplicationController
  before_filter :load_client

  def new
    #@client = Client.find(params[:client_id])
    @report = Report.new
  end

  def create
    #@client = Client.find(params[:client_id])
    @report = @client.reports.new(report_params)
    respond_to do |format|
      if @report.save
        #format.html { redirect_to client_report_path[@client, @report], notice: 'Report was successfully created.' }
        format.html { redirect_to client_path(@client), notice: 'Report was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end
  # def create
  #   @client = Client.find(params[:client_id])
  #   @report = Report.new(report_params)
  #   @report.save
  #   redirect_to root_path
  # end

  def index
    #@client = Client.find(params[:client_id])
    @reports = @client.reports.all
  end

  def show
  end

  def update
  end

  def destroy
    @client_reports = Report.find(params[:id])
    @client_reports.destroy
    respond_to do |format|
      format.html { redirect_to client_path(@client) }
      #format.json { head :no_content }
    end
  end

  protected

  def report_params
    params.require(:report).permit(:location, :client_id, :livingcondition, :gender, :ethnicity, :age, :needs, :notes)
  end

  def load_client
    @client = Client.find(params[:client_id])
  end



end

icount/app/helpers/application_helper.rb
module ApplicationHelper
end

icount/app/helpers/client_helper.rb
module ClientHelper
end

icount/app/helpers/main_helper.rb
module MainHelper
end

icount/app/helpers/report_helper.rb
module ReportHelper
end

icount/app/views/client/create.html.erb
<h1>Client#create</h1>
<p>Find me in app/views/client/create.html.erb</p>

icount/app/views/client/index.html.erb
<h1>Client List</h1>
<%# List of all clients should go here %>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
    <tbody>
    <% @clients.each do |client| %>
        <tr>
          <td><%= client.name %></td>
          <td><%= client.description %></td>
          <td><%= link_to 'Show', client %></td>
          <td><%= link_to 'Delete', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
    <% end %>
  </tbody>
</table>

<div class="row">
  <%=link_to "New Client", new_client_path, :class=>"button"%>
</div>

icount/app/views/client/new.html.erb
<h1>Input Client Data</h1>
<p>Add data on people in need and resources needed</p>

<%= simple_form_for @client, :url => client_index_path do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.button :submit %>
<% end %>

icount/app/views/client/show.html.erb
<h2>Client Reports</h2>

<p>
  <strong>Name:</strong>
  <%= @client.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @client.description %>
</p>

<table>
  <thead>
    <tr>
      <th>Location</th>
      <th>Living Condition</th>
      <th>Gender</th>
      <th>Ethnicity</th>
      <th>Age</th>
      <th>Needs</th>
      <th>Notes</th>
      <th></th>
    </tr>
  </thead>
    <tbody>

    <% @reports.each do |report| %>
        <tr>
          <td><%= report.location %></td>
          <td><%= report.livingcondition %></td>
          <td><%= report.gender %></td>
          <td><%= report.ethnicity %></td>
          <td><%= report.age %></td>
          <td><%= report.needs %></td>
          <td><%= report.notes %></td>
          <td><%= link_to 'Delete', client_report_path(report.client, report), method: :delete, data: { confirm: 'Are you sure?' } %></td>

        </tr>
   <!--        <td><%= report.livingcondition %></td> -->
          <!-- <td><%#= link_to 'Show', client %></td> -->
    <% end %>
  </tbody>
</table>


<%= link_to 'View Clients', client_index_path, :class => "button" %>
<%= link_to 'Add New Report', new_client_report_path(@client), :class => "button" %>

icount/app/views/client/update.html.erb
<h1>Client#update</h1>
<p>Find me in app/views/client/update.html.erb</p>

icount/app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie9" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "iCount App" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <p class="navbar-text pull-right">
    <% if iuser_signed_in? %>
      Logged in as <strong><%= current_iuser.email %></strong>.
      <%= link_to 'Edit profile', edit_iuser_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_iuser_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
      <%= link_to "Sign up", new_iuser_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_iuser_session_path, :class => 'navbar-link'  %>
    <% end %>

    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>

    
    <%= javascript_include_tag "application" %>
  </body>
</html>

icount/app/views/main/index.html.erb
<h2>WeCount App</h2>
<p> Record and Retreive data on People in Need</p>


<div class="row">
  <%=link_to "Enter Data", new_client_path, :class=>"button"%>
</div>
<div class="row">
  <%=link_to "View Clients", client_index_path, :class=>"button"%>
</div>

icount/app/views/report/create.html.erb
<h1>Report#create</h1>
<p>Find me in app/views/report/create.html.erb</p>

icount/app/views/report/index.html.erb
<h1>Report#index</h1>
<p>Find me in app/views/report/index.html.erb</p>

icount/app/views/report/new.html.erb
<h1>Input Report Data</h1>
<p>Add data on people in need and resources needed</p>

<%= simple_form_for [@client, @report], :url => client_report_index_path do |f| %>
  <%= f.input :location %>
  <%= f.input :livingcondition, :collection => ['Vehicle', 'Tent', 'Ground', 'Bridge/Overpass', 'Other'] %>
  <%= f.input :gender, :collection => ['Male', 'Female', 'Other'] %>
  <%= f.input :ethnicity, :collection => ['White', 'Black', 'Hispanic', 'Asian', 'Native American' 'Other'] %>
  <%= f.input :age, :collection => ['Under 18', '18-24', '25-40', '41-60', '60+', 'Unknown'] %>
  <%= f.input :needs %>
  <%= f.input :notes %>
  <%= f.button :submit %>
<% end %>

<div class="row">
  <%=link_to "Client List", client_index_path, :class=>"button"%>
</div>

<!--     add_column :reports, :livingcondition, :string
    add_column :reports, :gender, :string
    add_column :reports, :ethnicity, :string
    add_column :reports, :age, :string
    add_column :reports, :needs, :string -->

icount/app/views/report/show.html.erb
<h1>Report#show</h1>
<p>Find me in app/views/report/show.html.erb</p>

icount/app/views/report/update.html.erb
<h1>Report#update</h1>
<p>Find me in app/views/report/update.html.erb</p>